// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIAYIl4dubfNGn8OB9cljOIV3q2I1C-S0',
    appId: '1:335189487328:web:bace99cca395089aacea85',
    messagingSenderId: '335189487328',
    projectId: 'cthulhu-solo-investigator',
    authDomain: 'cthulhu-solo-investigator.firebaseapp.com',
    storageBucket: 'cthulhu-solo-investigator.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbKQqn-9cgdnlkPNJ67ylxdqT78ffwmQ',
    appId: '1:335189487328:android:500393397b7c8abeacea85',
    messagingSenderId: '335189487328',
    projectId: 'cthulhu-solo-investigator',
    storageBucket: 'cthulhu-solo-investigator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAs0btAjcyWdrb2TRMM7zQwMG5f2gbWLg',
    appId: '1:335189487328:ios:d2bba27effe81c71acea85',
    messagingSenderId: '335189487328',
    projectId: 'cthulhu-solo-investigator',
    storageBucket: 'cthulhu-solo-investigator.firebasestorage.app',
    iosClientId: '335189487328-s183gc3ek45uft4jh3j4s5bvljip6btg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cthulhuSoloInvestigatorHandbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAs0btAjcyWdrb2TRMM7zQwMG5f2gbWLg',
    appId: '1:335189487328:ios:f8080b6d8cc0ed17acea85',
    messagingSenderId: '335189487328',
    projectId: 'cthulhu-solo-investigator',
    storageBucket: 'cthulhu-solo-investigator.firebasestorage.app',
    iosClientId: '335189487328-2a5skdufr0d9njo7teirkla18j2evaoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.cthulhuSoloInvestigatorHandbook.RunnerTests',
  );
}
